const COLOR_SCHEME__SYSTEM = 'system';
const COLOR_SCHEME__LIGHT = 'light';
const COLOR_SCHEME__DARK = 'dark';

const BREAKPOINT__SM = '40rem';
const BREAKPOINT__MD = '48rem';
const BREAKPOINT__LG = '64rem';

export {
  COLOR_SCHEME__LIGHT,
  COLOR_SCHEME__SYSTEM,
  COLOR_SCHEME__DARK,
  BREAKPOINT__SM,
  BREAKPOINT__MD,
  BREAKPOINT__LG,
};
